export const LAYERS = [
  {
    name: 'The Foundation',
    period: 'Origin',
    quote: 'Before design, there was observation.',
    detail: 'Where curiosity became intention',
    color: '#3D2B1A',
    objects: ['First Brief', 'Sketchbook', 'The Eye'],
    y: 0,
  },
  {
    name: 'The Awakening',
    period: 'Early Work',
    quote: 'First client. First compromise. First lesson.',
    detail: 'Learning through making',
    color: '#4A6741',
    objects: ['Brand Mark', 'Late Invoice', 'Pixel Grid'],
    y: 6,
  },
  {
    name: 'The Discipline',
    period: 'Craft',
    quote: 'Systems over aesthetics. No\u2009\u2014\u2009both.',
    detail: 'Precision as philosophy',
    color: '#7A9E72',
    objects: ['Design System', 'The Grid', 'Component'],
    y: 12,
  },
  {
    name: 'The Break',
    period: 'The Shift',
    quote: 'The year I unlearned everything.',
    detail: 'Breaking to rebuild',
    color: '#C8B99A',
    objects: ['AI Prompt', 'Vibe Code', 'New Tools'],
    y: 18,
  },
  {
    name: 'The Studio',
    period: 'Now',
    quote: 'Soni Labs begins here.',
    detail: 'Present tense, future facing',
    color: '#E8E0CC',
    objects: ['Identity', 'The Work', "What's Next"],
    y: 24,
  },
];
